Repository Our-Voice-Inc/ourvoice, pull requests merged in 2023-07, with the labels that each got.

#59 Comment fix
  apps/ourvoice-api/src/modules/moderation/comment-moderation/comment-moderation.repository.ts
  apps/ourvoice-app/src/components/comment/CommentCard.vue
  apps/ourvoice-app/src/components/comment/CommentList.vue
  apps/ourvoice-app/src/components/comment/CommentTextarea.vue
  apps/ourvoice-app/src/components/common/Toast.vue
  apps/ourvoice-app/src/stores/comments.ts
Labels: bug, frontend

#66 feat(consent): added consent flow
  apps/ourvoice-api/src/auth/supertokens/supertokens.service.ts
  apps/ourvoice-api/src/modules/users/users.controller.ts
  apps/ourvoice-app/src/App.vue
  apps/ourvoice-app/src/components/common/ConsentModal.vue
  apps/ourvoice-app/src/services/user-service.ts
  apps/ourvoice-app/src/stores/user.ts
  apps/ourvoice-app/src/views/HomeView.vue
  apps/ourvoice-auth-api/src/auth/supertokens/supertokens.service.ts
  config/content/consent.md
Labels: frontend

#74 feat(admin): show user allow list in UI
  apps/ourvoice-admin/src/views/HomeView.vue
  apps/ourvoice-api/src/modules/users/metadata/metadata.service.ts
  apps/ourvoice-api/src/modules/users/users.controller.ts
  apps/ourvoice-app/src/components/common/ConsentModal.vue
  apps/ourvoice-app/src/stores/user.ts
  deployment/.env.template
  deployment/docker-compose-prod.yml
  deployment/docker-compose.yml
Labels: frontend, backend
